site_name: PhenoteFX


theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Developers: 'developers.md'
  - Authors: 'authors.md'
  - User guide:
      - Setup: 'tutorial_setup.md'
      - File menu: 'tutorial_file.md'
      - New entry: 'tutorial_create_new.md'
      - Adding annotations: 'tutorial_add_annotation.md'
      - Text mining: 'tutorial_text_mining.md'
      - Local HPO file: 'tutorial_local_hpo.md'
      - Sharing: 'tutorial_sharing.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables

copyright: |
  &copy; 2023 <a href="https://github.com/pnrobinson"  target="_blank" rel="noopener">Peter N Robinson</a>