name: mkdocs-generation
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11' # Explicit versions prevent unexpected breaking changes

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-material[imaging] pillow cairosvg mkdocs-material-extensions "mkdocstrings[python]"

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
